services:
  last-10-posts:
    image: lw89233/last_10_posts:latest
    container_name: last-10-posts-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${LAST_10_POSTS_MICROSERVICE_PORT}:${LAST_10_POSTS_MICROSERVICE_PORT}"